"""
Compare schwabdev.price_history() with a direct HTTP request to Schwab.

This is diagnostic code.

The goal is to determine whether unexpected price-history behavior comes
from:

    1. our requested parameters,
    2. schwabdev's price_history() wrapper, or
    3. Schwab's REST price-history endpoint.

Authentication/token management still comes from schwabdev through
mb_tools.schwab_secure.  The second market-data request bypasses
schwabdev.price_history() and calls Schwab directly with requests.
"""

from __future__ import annotations

import argparse
import getpass
import json
import os
from datetime import date, datetime, time
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlparse
from zoneinfo import ZoneInfo

import requests

from mb_tools.schwab_secure import (
    console_auth_callback,
    make_secure_schwab_client,
)


ET = ZoneInfo("America/New_York")

PRICE_HISTORY_URL = (
    "https://api.schwabapi.com/marketdata/v1/pricehistory"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Compare schwabdev price_history() with a direct Schwab "
            "price-history HTTP request."
        )
    )

    parser.add_argument(
        "--symbol",
        default="SPY",
        help="Symbol to probe. Default: SPY",
    )

    parser.add_argument(
        "--date",
        required=True,
        help="Trading date to inspect, YYYY-MM-DD.",
    )

    parser.add_argument(
        "--ecfg",
        help="Explicit path to secure_schwabdev.ecfg.",
    )

    parser.add_argument(
        "--timeout",
        type=int,
        default=10,
        help="HTTP timeout in seconds. Default: 10",
    )

    return parser.parse_args()


def resolve_ecfg(explicit_path: str | None) -> Path:
    candidates: list[Path] = []

    if explicit_path:
        candidates.append(Path(explicit_path).expanduser())

    env_ecfg = os.environ.get("MB_SCHWAB_ECFG")
    if env_ecfg:
        candidates.append(Path(env_ecfg).expanduser())

    mb_vault = os.environ.get("MB_VAULT")
    if mb_vault:
        candidates.append(
            Path(mb_vault).expanduser() / "secure_schwabdev.ecfg"
        )

    candidates.append(Path.cwd() / "secure_schwabdev.ecfg")

    for path in candidates:
        if path.is_file():
            return path.resolve()

    searched = "\n".join(f"  {path}" for path in candidates)

    raise FileNotFoundError(
        "Could not find secure_schwabdev.ecfg.\n"
        "Paths checked:\n"
        f"{searched}"
    )


def parse_trade_date(text: str) -> date:
    try:
        return date.fromisoformat(text)
    except ValueError as exc:
        raise SystemExit(
            f"Invalid --date {text!r}; expected YYYY-MM-DD."
        ) from exc


def et_datetime(
    trade_date: date,
    hour: int,
    minute: int,
) -> datetime:
    return datetime.combine(
        trade_date,
        time(hour=hour, minute=minute),
        tzinfo=ET,
    )


def epoch_ms(dt: datetime) -> int:
    """Independent epoch-millisecond conversion."""
    return int(dt.timestamp() * 1000)


def epoch_ms_to_et(value: int | str) -> datetime:
    return datetime.fromtimestamp(
        int(value) / 1000.0,
        tz=ET,
    )


def candle_dt_et(candle: dict[str, Any]) -> datetime:
    return epoch_ms_to_et(candle["datetime"])


def describe_response(
    label: str,
    response: requests.Response,
    data: dict[str, Any],
) -> None:
    candles = data.get("candles", [])

    print()
    print(label)
    print("=" * 79)
    print(f"HTTP status    : {response.status_code}")
    print(f"Candle count   : {len(candles)}")

    if candles:
        first = candle_dt_et(candles[0])
        last = candle_dt_et(candles[-1])

        print(
            f"First candle   : "
            f"{first:%Y-%m-%d %H:%M:%S %Z}"
        )
        print(
            f"Last candle    : "
            f"{last:%Y-%m-%d %H:%M:%S %Z}"
        )

    print(f"Symbol         : {data.get('symbol')!r}")
    print(f"Previous close : {data.get('previousClose')!r}")
    print(f"Empty          : {data.get('empty')!r}")


def print_wrapper_request(response: requests.Response) -> None:
    url = response.request.url

    print()
    print("Actual request generated by schwabdev")
    print("=" * 79)
    print(url)

    parsed = urlparse(url)
    query = parse_qs(parsed.query)

    print()
    print("Decoded schwabdev query parameters")
    print("=" * 79)

    for key in sorted(query):
        values = query[key]

        for value in values:
            if key in {"startDate", "endDate"}:
                decoded = epoch_ms_to_et(value)
                print(
                    f"{key:<23}: {value}  "
                    f"-> {decoded:%Y-%m-%d %H:%M:%S %Z}"
                )
            else:
                print(f"{key:<23}: {value}")


def compare_data(
    wrapper_data: dict[str, Any],
    direct_data: dict[str, Any],
) -> None:
    wrapper_candles = wrapper_data.get("candles", [])
    direct_candles = direct_data.get("candles", [])

    print()
    print("Comparison")
    print("=" * 79)

    print(
        f"Entire JSON equal       : "
        f"{wrapper_data == direct_data}"
    )

    print(
        f"Candle lists equal      : "
        f"{wrapper_candles == direct_candles}"
    )

    print(
        f"Wrapper candle count    : "
        f"{len(wrapper_candles)}"
    )

    print(
        f"Direct candle count     : "
        f"{len(direct_candles)}"
    )

    if wrapper_candles and direct_candles:
        wrapper_first = candle_dt_et(wrapper_candles[0])
        direct_first = candle_dt_et(direct_candles[0])

        wrapper_last = candle_dt_et(wrapper_candles[-1])
        direct_last = candle_dt_et(direct_candles[-1])

        print(
            f"First timestamps equal  : "
            f"{wrapper_first == direct_first}"
        )

        print(
            f"Last timestamps equal   : "
            f"{wrapper_last == direct_last}"
        )

    if wrapper_candles != direct_candles:
        print()
        print(
            "NOTE: Candle responses differ. "
            "Preserved raw JSON should be inspected."
        )


def main() -> int:
    args = parse_args()

    symbol = args.symbol.strip().upper()
    trade_date = parse_trade_date(args.date)
    ecfg_path = resolve_ecfg(args.ecfg)

    request_start = et_datetime(trade_date, 0, 30)
    request_end = et_datetime(trade_date, 10, 0)

    start_ms = epoch_ms(request_start)
    end_ms = epoch_ms(request_end)

    print()
    print("Schwab price-history transport probe")
    print("=" * 79)
    print(f"Symbol             : {symbol}")
    print(f"Trading date       : {trade_date}")
    print(
        f"Requested start    : "
        f"{request_start:%Y-%m-%d %H:%M:%S %Z}"
    )
    print(
        f"Requested end      : "
        f"{request_end:%Y-%m-%d %H:%M:%S %Z}"
    )
    print(f"Start epoch ms     : {start_ms}")
    print(f"End epoch ms       : {end_ms}")
    print(f"Encrypted config   : {ecfg_path}")

    # Verify our own epoch conversion before contacting Schwab.
    print()
    print("Independent epoch round trip")
    print("=" * 79)
    print(
        f"startDate -> "
        f"{epoch_ms_to_et(start_ms):%Y-%m-%d %H:%M:%S %Z}"
    )
    print(
        f"endDate   -> "
        f"{epoch_ms_to_et(end_ms):%Y-%m-%d %H:%M:%S %Z}"
    )

    password = getpass.getpass(
        "\nEncrypted config password: "
    )

    client = None

    try:
        client = make_secure_schwab_client(
            ecfg_path,
            password,
            timeout=args.timeout,
            call_on_auth=console_auth_callback,
        )

        # -------------------------------------------------------------
        # Request 1: normal schwabdev wrapper
        # -------------------------------------------------------------

        print()
        print("Request 1: schwabdev.price_history() ...")

        wrapper_response = client.price_history(
            symbol,
            frequencyType="minute",
            frequency=5,
            startDate=request_start,
            endDate=request_end,
            needExtendedHoursData=True,
            needPreviousClose=True,
        )

        print_wrapper_request(wrapper_response)

        if not wrapper_response.ok:
            print()
            print("schwabdev request failed.")
            print(wrapper_response.text)
            return 1

        wrapper_data = wrapper_response.json()

        describe_response(
            "schwabdev response",
            wrapper_response,
            wrapper_data,
        )

        # -------------------------------------------------------------
        # Request 2: direct requests.get() to Schwab
        #
        # We use the access token already obtained/refreshed by
        # schwabdev, but we independently construct the endpoint,
        # query parameters, and HTTP request.
        # -------------------------------------------------------------

        direct_params = {
            "symbol": symbol,
            "frequencyType": "minute",
            "frequency": 5,
            "startDate": start_ms,
            "endDate": end_ms,
            "needExtendedHoursData": True,
            "needPreviousClose": True,
        }

        access_token = client.tokens.access_token

        direct_headers = {
            "Authorization": f"Bearer {access_token}",
        }

        print()
        print("Request 2: direct requests.get() ...")

        direct_response = requests.get(
            PRICE_HISTORY_URL,
            params=direct_params,
            headers=direct_headers,
            timeout=args.timeout,
        )

        print()
        print("Actual direct request")
        print("=" * 79)
        print(direct_response.request.url)

        if not direct_response.ok:
            print()
            print("Direct request failed.")
            print(direct_response.text)
            return 1

        direct_data = direct_response.json()

        describe_response(
            "Direct Schwab HTTP response",
            direct_response,
            direct_data,
        )

        compare_data(wrapper_data, direct_data)

        # -------------------------------------------------------------
        # Preserve evidence
        # -------------------------------------------------------------

        run_stamp = datetime.now(ET).strftime(
            "%Y-%m-%d-%H-%M-%S"
        )

        run_dir = (
            Path("output")
            / "transport_probe"
            / f"{run_stamp}-{symbol}-{trade_date}"
        )

        run_dir.mkdir(parents=True, exist_ok=True)

        wrapper_path = run_dir / "wrapper_response.json"
        direct_path = run_dir / "direct_response.json"
        report_path = run_dir / "transport_report.json"

        with wrapper_path.open(
            "w",
            encoding="utf-8",
        ) as file:
            json.dump(
                wrapper_data,
                file,
                indent=2,
                sort_keys=True,
            )

        with direct_path.open(
            "w",
            encoding="utf-8",
        ) as file:
            json.dump(
                direct_data,
                file,
                indent=2,
                sort_keys=True,
            )

        report = {
            "symbol": symbol,
            "trade_date": str(trade_date),
            "requested_start_et": request_start.isoformat(),
            "requested_end_et": request_end.isoformat(),
            "start_epoch_ms": start_ms,
            "end_epoch_ms": end_ms,
            "wrapper_request_url": wrapper_response.request.url,
            "direct_request_url": direct_response.request.url,
            "wrapper_http_status": wrapper_response.status_code,
            "direct_http_status": direct_response.status_code,
            "wrapper_candle_count": len(
                wrapper_data.get("candles", [])
            ),
            "direct_candle_count": len(
                direct_data.get("candles", [])
            ),
            "entire_json_equal": wrapper_data == direct_data,
            "candle_lists_equal": (
                wrapper_data.get("candles", [])
                == direct_data.get("candles", [])
            ),
        }

        with report_path.open(
            "w",
            encoding="utf-8",
        ) as file:
            json.dump(
                report,
                file,
                indent=2,
                sort_keys=True,
            )

        print()
        print("Saved evidence")
        print("=" * 79)
        print(f"Wrapper JSON : {wrapper_path}")
        print(f"Direct JSON  : {direct_path}")
        print(f"Report       : {report_path}")

    finally:
        if client is not None:
            client.close()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
